<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="QueryAction"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="106.966">
  <properties />
            <testcase name="verifyStatusLink" time="0.093" classname="tests.QueryActionTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
expected [185349] but found [1]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
expected [185349] but found [1]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
  steps.ActiveProjectsSteps.verifyingStatusLnkSteps(ActiveProjectsSteps.java:105)
  tests.QueryActionTest.verifyStatusLink(QueryActionTest.java:70)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:771)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
  org.testng.TestNG.run(TestNG.java:1032)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="sendQuery" time="5.048" classname="tests.QueryActionTest" />
                <testcase name="verifyQueryLink" time="0.123" classname="tests.QueryActionTest" />
                <testcase name="loginWithValidCredentials" time="91.386" classname="tests.QueryActionTest" />
                <testcase name="verifyValidationMessage" time="8.100" classname="tests.QueryActionTest" />
                <testcase name="statusVerificationAfterClickOnCloseBtn" time="2.216" classname="tests.QueryActionTest" />
      
</testsuite>
